### PR TITLE
Remove 'idle-vue' component from base build

### PR DESCRIPTION
**Pull request by GregPeden**
Per this issue: https://github.com/soixantecircuits/idle-vue/issues/27

This removes the idle-vue component from the base build to save on the package size. It cuts it down from about 13kb to 4kb before gzip compression.

### CODE REVIEW

**Comment by SirLamer** [comment]
Just a reminder that this is just sitting here waiting for adoption.

**Comment by blalan** [comment]
This looks great! Can we get this merged?

**Comment by SirLamer** [comment]
The package author indicated in a separate issue thread that they would accept this PR but there has been no activity since.

In the meantime, if you want, you can grab this package from here.

https://github.com/SirLamer/idle-vue/tree/remove-example-component

Keep in mind that I may remove this one day if the code is ever merged in to this project.

**Comment by gabrielstuff** [comment]
Hello @SirLamer, after a long reflexion :) I'll merge this.
The component does not have to do anything in there and should be released in a separate component.

Thanks for your contribution.

**Comment by GregPeden** [comment]
Thanks for merging! Don't forget to publish. ;-)

**Pull request merged**
